# Content source for gablehome.app — one entry per maintenance task.
# months: 1-12 when the task belongs on that month's checklist (northern hemisphere).
# interval: human phrase used on how-often pages and answer boxes.
# Copy rule: plain, useful, faceless. Every "why" earns its place or gets cut.

TASKS = [
    dict(slug="hvac-filter", name="Replace the HVAC filter", system="Heating & cooling",
         interval="Every 90 days", months=[1, 4, 7, 10],
         why="A clogged filter makes the blower work harder, raises energy use, and lets dust bypass into the ductwork. In homes with pets or allergies, the filter loads up even faster.",
         how="Check the size printed on the filter frame (like 16x25x1), buy the same size, and insert the new one with the airflow arrow pointing toward the unit. Write the date on the frame with a marker.",
         late="Weak airflow from vents, a dusty smell when the system starts, and rising energy bills are the usual signs a filter is overdue."),
    dict(slug="smoke-detector-test", name="Test smoke and CO detectors", system="Safety",
         interval="Every month", months=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
         why="Detectors fail quietly — the only way to know one still works is to test it. Working smoke alarms cut the risk of dying in a home fire roughly in half.",
         how="Press and hold the test button on each unit until the alarm sounds. Replace any unit that fails, and replace every detector older than ten years — the sensor degrades even if the beep still works.",
         late="There is no visible sign of a dead detector. That is the point of testing."),
    dict(slug="detector-batteries", name="Replace detector batteries", system="Safety",
         interval="Once a year", months=[10],
         why="A chirping detector gets its battery pulled at 2 a.m. and never replaced. Doing the whole house on one date each year removes the guesswork.",
         how="Replace the batteries in every smoke and CO detector on the same day, even the ones that haven't chirped. Many people tie it to the fall clock change.",
         late="Chirping at night — or a silent detector that no longer chirps at all."),
    dict(slug="gutter-cleaning", name="Clean the gutters", system="Roof & exterior",
         interval="Twice a year — spring and after leaf drop", months=[4, 11],
         why="Blocked gutters overflow against the fascia and foundation, which is how a handful of leaves becomes rot, ice dams, and a wet basement.",
         how="Scoop debris out by hand or with a gutter tool, then flush with a hose and watch that each downspout runs clear and discharges at least a meter from the foundation.",
         late="Plants growing in the gutter, water sheeting over the edge in rain, or staining on the siding below."),
    dict(slug="water-heater-flush", name="Flush the water heater", system="Plumbing",
         interval="Once a year", months=[9],
         why="Sediment settles at the bottom of the tank, insulating the water from the burner and corroding the liner. A flushed tank heats faster and lasts years longer.",
         how="Turn the heater to vacation mode, connect a garden hose to the drain valve, and drain until the water runs clear. Close the valve, refill, and restore the setting.",
         late="Rumbling or popping sounds from the tank, cloudy hot water, or hot water that runs out faster than it used to."),
    dict(slug="dryer-vent", name="Clean the dryer vent duct", system="Laundry",
         interval="Once a year", months=[3],
         why="Lint in the exhaust duct is one of the leading causes of house fires, and a choked vent makes every load take two cycles instead of one.",
         how="Pull the dryer out, disconnect the duct, and clear it end to end with a brush kit or vacuum. Check that the outside flap opens freely when the dryer runs.",
         late="Loads taking longer to dry, a hot laundry room, or a burning smell while the dryer runs."),
    dict(slug="gfci-test", name="Test GFCI outlets", system="Safety",
         interval="Every 3 months", months=[1, 4, 7, 10],
         why="GFCI outlets protect the wet areas of the house from shock, and their internal mechanism can fail while the outlet keeps delivering power.",
         how="Press the TEST button on each GFCI outlet in kitchens, bathrooms, garage, and outdoors. The outlet should go dead; press RESET to restore it. Replace any outlet that doesn't trip.",
         late="No visible sign — a failed GFCI looks and works like a healthy outlet until the moment it matters."),
    dict(slug="fridge-coils", name="Vacuum the refrigerator coils", system="Kitchen",
         interval="Every 6 months", months=[5, 11],
         why="Dust-blanketed condenser coils force the compressor to run longer and hotter, which shows up in the electric bill first and the repair bill later.",
         how="Pull the fridge out or pop off the base grille, and vacuum the coils with a brush attachment until the metal shows.",
         late="The fridge running constantly, warm sides, or the compressor cycling loudly."),
    dict(slug="dishwasher-filter", name="Clean the dishwasher filter", system="Kitchen",
         interval="Every 2 months", months=[2, 4, 6, 8, 10, 12],
         why="Modern dishwashers trap food in a filter you're supposed to rinse — few people know it exists. A loaded filter is why glasses come out gritty and the machine smells.",
         how="Twist the filter out of the tub floor, rinse it under hot water, and scrub the mesh with a soft brush before reseating it.",
         late="Grit on dishes, standing water after a cycle, or a sour smell when the door opens."),
    dict(slug="washer-hoses", name="Inspect washing machine hoses", system="Laundry",
         interval="Every 6 months", months=[6, 12],
         why="A burst supply hose floods a laundry room in minutes and is consistently among the most common causes of home water damage claims.",
         how="Look for bulges, cracks, or rust at the connections, and replace rubber hoses older than five years — braided stainless versions are inexpensive insurance.",
         late="Any bulge or drip is already an emergency in slow motion. Replace the hose, don't watch it."),
    dict(slug="sump-pump-test", name="Test the sump pump", system="Basement",
         interval="Twice a year — before wet seasons", months=[3, 10],
         why="A sump pump spends most of its life idle and is only discovered dead during the storm that needed it.",
         how="Pour a bucket of water into the pit and confirm the pump starts, drains the pit, and shuts off. If it has a battery backup, test that too.",
         late="There is no warning sign short of a flooded basement — testing is the warning sign."),
    dict(slug="hose-bib-winterize", name="Shut off and drain outdoor faucets", system="Plumbing",
         interval="Every fall before first freeze", months=[10],
         why="Water trapped in an exterior faucet freezes, expands, and splits the pipe inside the wall — the leak only shows up the following spring.",
         how="Close the interior shutoff valve for each hose bib, then open the outside tap and let it drain. Disconnect and drain garden hoses.",
         late="A hose bib that sprays inside the wall when first opened in spring means last winter already won."),
    dict(slug="chimney-sweep", name="Have the chimney swept", system="Heating & cooling",
         interval="Once a year if you burn wood", months=[9],
         why="Creosote builds up in the flue with every fire and is the fuel for chimney fires. Inspection also catches flue cracks and blocked caps.",
         how="Book a certified chimney sweep in late summer or early fall, before the seasonal rush. Between visits, burn only dry, seasoned wood.",
         late="Strong smoky odor from the fireplace, black flakes falling into the firebox, or smoke entering the room."),
    dict(slug="garage-door", name="Lubricate and test the garage door", system="Exterior",
         interval="Every 6 months", months=[4, 10],
         why="The garage door is the heaviest moving object in the house. Dry rollers and springs wear fast, and a failed auto-reverse is a genuine safety hazard.",
         how="Spray rollers, hinges, and springs with garage-door lubricant. Test auto-reverse by laying a board under the closing door — it must reverse on contact.",
         late="Squealing or grinding on open, jerky travel, or a door that slams the last half meter."),
    dict(slug="water-shutoff", name="Exercise the main water shutoff", system="Plumbing",
         interval="Once a year", months=[2],
         why="In a burst-pipe emergency the main valve is the difference between a puddle and a disaster — unless it seized open years ago.",
         how="Close the main valve fully, then reopen it. If it's stiff, work it gently back and forth; if it won't move or weeps, have it replaced on your schedule instead of during a flood.",
         late="A valve that hasn't been turned in years should be assumed stuck until proven otherwise."),
    dict(slug="bathroom-caulk", name="Inspect tub and shower caulk", system="Bathrooms",
         interval="Every 6 months", months=[3, 9],
         why="Failed caulk lets shower water into the wall cavity, where it rots framing and feeds mold invisibly. Recaulking costs a few dollars; the wall repair costs thousands.",
         how="Check the caulk lines around tubs, showers, and sinks for cracks, gaps, and mold that cleaning won't remove. Strip and recaulk failed sections with kitchen-and-bath caulk.",
         late="Spongy wall tile, peeling paint on the ceiling below a bathroom, or a musty smell that returns after cleaning."),
    dict(slug="toilet-leak-test", name="Check toilets for silent leaks", system="Bathrooms",
         interval="Once a year", months=[8],
         why="A worn flapper lets water seep from tank to bowl around the clock — silent, invisible, and often hundreds of liters a day on the water bill.",
         how="Put a few drops of food coloring in the tank and wait 15 minutes without flushing. Color in the bowl means the flapper needs replacing — a five-minute job.",
         late="A water bill that creeps up, or a toilet that refills briefly on its own ('ghost flushing')."),
    dict(slug="roof-inspection", name="Inspect the roof from the ground", system="Roof & exterior",
         interval="Twice a year and after big storms", months=[5, 11],
         why="One lifted shingle is a cheap repair; the same shingle after two rainy seasons is a ceiling stain and a mold problem.",
         how="Walk the perimeter with binoculars. Look for missing or curling shingles, damaged flashing at chimneys and vents, moss patches, and granules collecting in gutters.",
         late="Granules filling the gutters, daylight in the attic, or water stains on top-floor ceilings."),
    dict(slug="deck-inspection", name="Inspect and clean the deck", system="Roof & exterior",
         interval="Once a year", months=[5],
         why="Deck fasteners loosen and boards rot from the underside first. The failure mode is sudden, and it happens under load.",
         how="Check for soft spots, popped fasteners, wobbly railings, and rot where posts meet the ground. Wash off grime; reseal when water stops beading on the surface.",
         late="Springy boards, leaning railings, or fastener heads standing proud of the wood."),
    dict(slug="window-seals", name="Check weatherstripping and caulk", system="Windows & doors",
         interval="Every fall", months=[9],
         why="Gaps around windows and doors leak heated air all winter and cooled air all summer — usually the cheapest energy fix in the whole house.",
         how="Check door weatherstripping for compression and daylight, and exterior window caulk for cracks. Replace flattened weatherstrip and recaulk failed joints on a dry day.",
         late="Drafts you can feel with the back of a hand, whistling on windy days, or condensation between panes."),
    dict(slug="ceiling-fan-direction", name="Reverse ceiling fan direction", system="Interior",
         interval="Twice a year", months=[5, 10],
         why="Counterclockwise pushes a cooling breeze down in summer; clockwise on low pulls warm air off the ceiling in winter. Same fan, two seasons of use.",
         how="Flip the small direction switch on the motor housing (or in the fan's app). Dust the blades while you're up there.",
         late="Not dangerous — just paying to heat the ceiling."),
    dict(slug="foundation-check", name="Walk the foundation after heavy rain", system="Roof & exterior",
         interval="Once a year", months=[4],
         why="Water pooling against the house is the root cause behind most wet basements and settling cracks. Grading fixes are cheap before they're urgent.",
         how="After a hard rain, look for pooling at the foundation, soil sloping toward the house, downspouts dumping at the wall, and new cracks wider than a coin.",
         late="Damp basement corners, efflorescence (white mineral bloom) on basement walls, or doors that stop closing squarely."),
    dict(slug="irrigation-winterize", name="Winterize the irrigation system", system="Yard",
         interval="Every fall before first freeze", months=[10],
         why="Water left in irrigation lines freezes and splits pipes, valves, and backflow preventers underground where you can't see the damage until spring.",
         how="Shut off the irrigation supply and drain the zones — or have the system blown out with compressed air, which is the only sure method in cold climates.",
         late="A zone that geysers or dribbles at spring startup means a split line from last winter."),
    dict(slug="mower-winterize", name="Winterize lawn equipment", system="Yard",
         interval="Every fall", months=[11],
         why="Fuel left in a mower over winter gums the carburetor — stale gas is the number one reason small engines refuse to start in spring.",
         how="Run the tank dry or add fuel stabilizer and run the engine to distribute it. Clean the deck, disconnect batteries, and store them somewhere that doesn't freeze.",
         late="A spring of pull-cord frustration and a carburetor cleaning bill."),
    dict(slug="ac-service", name="Service the AC before summer", system="Heating & cooling",
         interval="Once a year", months=[4],
         why="A serviced system cools better on less electricity, and technicians have open schedules in spring — not during the first heat wave.",
         how="Clean the outdoor condenser coils, clear vegetation to half a meter around the unit, and book a professional tune-up that checks refrigerant charge.",
         late="Weak cooling on hot afternoons, ice on the refrigerant lines, or the unit running without stopping."),
    dict(slug="furnace-service", name="Service the furnace before winter", system="Heating & cooling",
         interval="Once a year", months=[9],
         why="A fall tune-up catches failing igniters, cracked heat exchangers, and blocked flues before the first cold night — and keeps most warranties valid.",
         how="Book a professional service in early fall. Between visits, keep the filter fresh and the area around the furnace clear.",
         late="Short cycling, a yellow burner flame instead of blue, or the smell of combustion in the house — the last two mean call someone today."),
    dict(slug="exhaust-fans", name="Clean bathroom exhaust fans", system="Bathrooms",
         interval="Every 6 months", months=[2, 8],
         why="A dust-choked fan can't clear shower moisture, and chronic bathroom moisture becomes ceiling mold and peeling paint.",
         how="Pull the grille, vacuum the dust mat off the blades and cover, and confirm the fan actually moves air — a square of toilet paper should stick to the running grille.",
         late="Mirrors staying fogged long after showers, or specks of mold on the ceiling."),
    dict(slug="pest-entry", name="Seal pest entry points", system="Roof & exterior",
         interval="Every fall", months=[9],
         why="Mice need a gap the width of a pencil. Fall is when they move indoors, and exclusion beats trapping every time.",
         how="Inspect where pipes and cables enter the house, door sweeps, and foundation vents. Seal small gaps with sealant and larger ones with steel wool plus sealant.",
         late="Droppings in the garage or pantry, or scratching in walls at night."),
    dict(slug="freezer-defrost", name="Defrost the freezer and check seals", system="Kitchen",
         interval="Once a year", months=[1],
         why="Frost buildup steals capacity and makes the compressor run long; a leaking door seal causes both.",
         how="Defrost if frost is thicker than half a centimeter. Test the gasket by closing the door on a banknote — it should hold with light resistance all the way around.",
         late="Frost growing back within weeks, or the freezer running constantly."),
    dict(slug="range-hood-filter", name="Degrease the range hood filter", system="Kitchen",
         interval="Every 3 months", months=[3, 6, 9, 12],
         why="A grease-saturated filter stops capturing cooking exhaust and becomes a fire risk sitting directly over the burners.",
         how="Drop the mesh filter into hot water with degreaser or run it through the dishwasher, then dry and reseat it.",
         late="Grease dripping from the hood edge, or a kitchen that stays smoky when you cook."),
    dict(slug="radiator-bleed", name="Bleed radiators and check boiler pressure", system="Heating & cooling",
         interval="Every fall", months=[10],
         why="Trapped air keeps hot water out of the top of a radiator — the classic 'cold on top' symptom that wastes fuel all winter.",
         how="With the system off and cool, open each radiator's bleed valve until water spits, then close it. Check the boiler gauge afterwards and top up to the green band if needed.",
         late="Radiators cold at the top while hot at the bottom, or gurgling pipes."),
    dict(slug="snow-equipment", name="Get snow equipment ready", system="Yard",
         interval="Every fall", months=[11],
         why="The first storm is the worst possible time to discover the snow blower won't start and the stores are sold out of ice melt.",
         how="Start the snow blower, check the shear pins and keep spares, and lay in ice melt and a decent shovel before the season begins.",
         late="Shoveling wet snow at dawn while the blower sits dead in the garage."),
    dict(slug="siding-wash", name="Wash siding and check paint", system="Roof & exterior",
         interval="Once a year", months=[6],
         why="Grime feeds mildew, and failed paint exposes bare wood — rot starts wherever water finds unprotected material.",
         how="Rinse the siding with a garden hose and soft brush (pressure washers force water behind boards). Note peeling paint, cracked boards, and gaps at trim for repair.",
         late="Green film on shaded walls, curling paint, or soft spots at trim joints."),
    dict(slug="driveway-cracks", name="Fill driveway and walkway cracks", system="Roof & exterior",
         interval="Once a year", months=[7],
         why="Water in a crack becomes frost heave in winter — small cracks grow into broken slabs one freeze at a time.",
         how="Clean cracks out and fill with the right filler for asphalt or concrete on a dry summer day. Reseal asphalt driveways every few years.",
         late="Cracks widening year over year, or slab edges lifting unevenly."),
    dict(slug="humidifier-clean", name="Clean humidifiers and dehumidifiers", system="Interior",
         interval="Every 3 months in season", months=[1, 7],
         why="Both machines hold standing water, and standing water grows mold and bacteria that the machine then distributes through the house.",
         how="Empty and scrub the tank, replace evaporator pads or clean coils per the manual, and let parts dry fully before reassembly.",
         late="A damp or musty smell when the machine runs — that smell is biology, not dust."),
    dict(slug="tree-trimming", name="Trim branches away from the house", system="Yard",
         interval="Once a year", months=[11],
         why="Branches touching the roof abrade shingles with every breeze, drop debris into gutters, and give squirrels and ants a bridge into the house.",
         how="Cut back anything touching or overhanging the roofline; late fall, with leaves down, is the easiest time to see structure. Leave big limbs near power lines to professionals.",
         late="Scratching sounds on the roof in wind, moss where a branch shades the shingles."),
    dict(slug="fire-extinguisher", name="Check fire extinguishers", system="Safety",
         interval="Every 6 months", months=[6, 12],
         why="An extinguisher with a dead gauge is decor. Kitchens, garages, and each floor deserve a working one within reach.",
         how="Confirm the needle is in the green, the pin and seal are intact, and nothing blocks access. Replace units older than 10–12 years or after any use.",
         late="A needle out of the green zone, or an extinguisher buried behind holiday boxes."),
]

SEASONS = {
    "spring": dict(months=[3, 4, 5], title="Spring Home Maintenance Checklist",
                   blurb="Winter is what your house just survived; spring is when you find out how it went. This season is about drainage, inspection, and getting cooling ready before the first hot week."),
    "summer": dict(months=[6, 7, 8], title="Summer Home Maintenance Checklist",
                   blurb="Long days and dry weather make summer the season for exterior work — washing, sealing, and the repairs you noted in spring."),
    "fall": dict(months=[9, 10, 11], title="Fall Home Maintenance Checklist",
                 blurb="Fall is the busiest maintenance season: everything that freezes must be drained, everything that heats must be serviced, and everything that fell from the trees must leave the gutters."),
    "winter": dict(months=[12, 1, 2], title="Winter Home Maintenance Checklist",
                   blurb="Winter maintenance moves indoors: safety checks, appliances, and the small interior jobs there's finally time for."),
}

MONTH_NAMES = ["", "January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]
